// location
const locationButton = document.getElementById("location-btn");
const locationPopup = document.getElementById("location-popup");
const newPopupButtonClose = document.getElementById("new-popup-button-close");
const cityList = document.getElementById("city-list");

locationButton.addEventListener("click", () => {
  locationPopup.classList.add("visible");
});

newPopupButtonClose.addEventListener("click", () => {
  locationPopup.classList.remove("visible");
});

cityList.addEventListener("click", (event) => {
  const cityItem = event.target.closest(".city-item");
  if (cityItem) {
    const cityName = cityItem.getAttribute("data-city");
    locationButton.textContent = cityName;
    locationPopup.classList.remove("visible");
  }
});
// view al city
document.addEventListener("DOMContentLoaded", () => {
  // Elements for the first and second popups
  const dropdownButton = document.getElementById("dropdown-button");
  const locationSelector = document.getElementById("location-selector");
  const closeButton = document.getElementById("close-button");
  const viewAllButton = document.getElementById("view-all-button");
  const allCitiesDropdown = document.getElementById("all-cities-dropdown");
  const allCloseButton = document.getElementById("all-close-button");
  const allCityList = document.getElementById("all-city-list");
  const allSearchBar = document.getElementById("all-search-bar");
  const alphabetFilter = document.getElementById("alphabet-filter");

  // List of all cities
  const allCities = [
    "Agra",
    "Ahmedabad",
    "Abhanpur",
    "Abohar",
    "Achanta",
    "Adaspur",
    "Addanki",
    "Adilabad",
    "Adimali",
    "Adoni",
    "Adoor",
    "Afzalpu",
    "Agartala",
    "Agomani",
    "Agra",
    "Agra Outer",
    "Agroha",
    "Ahmadpur",
    "Ahmedabad",
    "Ahmednagar",
    "Ahwa",
    "Aizawl",
    "Ajmer",
    "Ajnala",
    "Akaltara",
    "Akbarpur",
    "Akhnoor",
    "Akividu",
    "Akkalkot",
    "Akluj",
    "Akola",
    "Akola Bazar",
    "Akole",
    "Akot",
    "Alampur",
    "Aland",
    "Alappuzha",
    "Alathur",
    "Alephata",
    "Aler",
    "Alibag",
    "Aliganj",
    "Aligarh",
    "Alipurduar",
    "Alirajpur",
    "Allagadda",
    "Allavaram",
    "Almora",
    "Alur",
    "Aluva",
    "Alwar",
    "Alwar Outer",
    "Amadalavalasa",
    "Amakhokhara",
    "Amalapuram",
    "Amanganj",
    "Amaravati",
    "Amarpur",
    "Amarwara",
    "Amb",
    "Ambah",
    "Ambajogai",
    "Ambala",
    "Ambala Outer",
    "Ambasamudram",
    "Ambedkar Nagar",
    "Ambegaon",
    "Ambikapur",
    "Ambur",
    "Amethi",
    "Amravati",
    "Amreli",
    "Amritsar",
    "Amroha",
    "Anakapalle",
    "Anand",
    "Anandnagar",
    "Anandpur Sahib",
    "Ananthapur",
    "Ananthnag",
    "Ander",
    "Angamaly",
    "Angaragaon",
    "Angul",
    "Anjar",
    "Ankleshwar",
    "Ankola",
    "Annavaram",
    "Anni",
    "Anpara",
    "Antah",
    "Anthiyur",
    "Anupgarh",
    "Anuppur",
    "Anupshahar",
    "Aonia",
    "Aonla",
    "Arakalagud",
    "Arakandanallur",
    "Arakkonam",
    "Arambag",
    "Aranthangi",
    "Araria",
    "Areekode",
    "Ariyalur",
    "Armoor",
    "Arni",
    "Arrah",
    "Arsikere",
    "Aruppukkottai",
    "Arwal",
    "Asangaon",
    "Asansol",
    "Asansol Outer",
    "Ashok Nagar",
    "Ashta",
    "Asifabad",
    "Asika",
    "Assandh",
    "Astaranga",
    "Atarra",
    "Athani",
    "Athner",
    "Atmakur",
    "Atrauly",
    "Attingal",
    "Attur",
    "Aurad",
    "Aurai",
    "Auraiya",
    "Aurangabad",
    "Aurangabad-BR",
    "Avanigadda",
    "Avinashi",
    "Ayoor",
    "Azamgarh",
    "Kothakota",
    "Aberu ",
    "Abra ",
    "Abrala ",
    "Abujang ",
    "Badagada ",
    "Badamba ",
    "Badami ",
    "Baddi ",
    "Badnagar ",
    "Badnaur ",
    "Badvel ",
    "Bagalkot ",
    "Bagbahra ",
    "Bagdogra ",
    "Bagepalli ",
    "Bageshwar ",
    "Bagha Purana ",
    "Baghpat ",
    "Bagidora ",
    "Bagnan ",
    "Bagodar ",
    "Bagodara ",
    "Bah ",
    "Bahadurgarh ",
    "Bahalda ",
    "Baharampur ",
    "Bahraich ",
    "Baikunthpur ",
    "ailaha ",
    "Bailhongal ",
    "Baisinga ",
    "Bajag ",
    "Baksha ",
    "Balagarh ",
    "Balaghat ",
    "Balangir ",
    "Balasinor ",
    "Balasore ",
    "Balej ",
    "Baleswar ",
    "Baliapal ",
    "Balichak ",
    "Balighat ",
    "Balimela ",
    "Balipara ",
    "Ballarpur ",
    "Ballia ",
    "Ballia Outer ",
    "Balliguda ",
    "Ballinga ",
    "Bally ",
    "Balod ",
    "Balotra ",
    "Balrampur ",
    "Balrampur-CG ",
    "Balugaon ",
    "Balurghat ",
    "Bamra ",
    "Banaganapalli ",
    "Banda ",
    "Banda-MP ",
    "Bangalore ",
    "Bangalore Outer ",
    "Bangana ",
    "Bangarapet ",
    "Bangarmau ",
    "Banka ",
    "Bankura ",
    "Banmankhi Bazar ",
    "Bansda ",
    "Bansdih ",
    "Bansur ",
    "Banswada ",
    "Banswara ",
    "Bantwal ",
    "Bapatla ",
    "Barabanki ",
    "Barachatti ",
    "Baramati ",
    "Baramkela ",
    "Baramulla ",
    "Baran ",
    "Barara ",
    "Barasat ",
    "Barauni ",
    "Baraut ",
    "Barbigha ",
    "Barbil ",
    "Bardez ",
    "Bardhaman ",
    "Bardoli ",
    "Bareilly ",
    "Bareilly Outer ",
    "Bargarh ",
    "Barh ",
    "Barhalganj ",
    "Barhampur ",
    "Bari ",
    "Baripada ",
    "Barki Saria ",
    "Barmer ",
    "Barnala ",
    "Barobisha ",
    "Baroda/Vadodara ",
    "Barpeta ",
    "Barrackpore ",
    "Barshi ",
    "Baruipur ",
    "Barwadih ",
    "Barwani ",
    "Basavakalyan ",
    "Basavana Bagewadi ",
    "Basirhat ",
    "Basmat ",
    "Basna ",
    "Basopatti ",
    "Bastar ",
    "Basti ",
    "Batala ",
    "Batlagundu ",
    "Bavla ",
    "Bayad ",
    "Beas ",
    "Beawar ",
    "Becharaji ",
    "Beed ",
    "Begowal ",
    "Begumganj ",
    "Begusarai ",
    "Behali ",
    "Behat ",
    "Behror ",
    "Belaganj ",
    "Belgaum ",
    "Bellamkonda ",
    "Bellampalli ",
    "Bellary ",
    "Belur ",
    "Benipatti ",
    "Benipur ",
    "Berhampore ",
    "Berla ",
    "Bero ",
    "Betamcherla ",
    "Betnoti ",
    "Bettiah ",
    "Betul ",
    "Bewar ",
    "Bhachau ",
    "Bhadaur ",
    "Bhadohi ",
    "Bhadra ",
    "Bhadrachalam ",
    "Bhadrak ",
    "Bhadravati ",
    "Bhadravati-KA ",
    "Bhaga ",
    "Bhagabanpur ",
    "Bhagalpur ",
    "Bhainsa ",
    "Bhalki ",
    "Bhandara ",
    "Bhanjanagar ",
    "Bhanupratappur ",
    "Bhanvad ",
    "Bharatpur ",
    "Bharatpur ",
    "Bharuch ",
    "Bharuwa Sumerpur ",
    "Bharwara ",
    "Bhatapara ",
    "Bhatewar ",
    "Bhatgaon ",
    "Bhathat ",
    "Bhatinda ",
    "Bhatinda Outer ",
    "Bhatkal ",
    "Bhattu ",
    "Bhavnagar ",
    "Bhawanipur Rajdham ",
    "Bhawarna ",
    "Bheden ",
    "Bheemunipatnam ",
    "Bhergaon ",
    "Bhesan ",
    "Bhikhiwind ",
    "Bhilad ",
    "Bhilai ",
    "Bhiloda ",
    "Bhilwara ",
    "Bhimadole ",
    "Bhimavaram ",
    "Bhind ",
    "Bhinder ",
    "Bhinga ",
    "Bhinmal ",
    "Bhiwadi ",
    "Bhiwadi Outer ",
    "Bhiwandi ",
    "Bhiwani ",
    "Bhogapuram ",
    "Bhojpur ",
    "Bhongir ",
    "Bhoom ",
    "Bhopal ",
    "Bhopalgarh ",
    "Bhore ",
    "Bhuban ",
    "Bhubaneswar ",
    "Bhuj ",
    "Bhusawal ",
    "Bhutasarasingi ",
    "Bhuvanagiri ",
    "Bichhiya ",
    "Bicholim ",
    "Bidar ",
    "Bighapur ",
    "Bihar Sharif ",
    "Bihta ",
    "Bijainagar ",
    "Bijanbari ",
    "Bijapur ",
    "Bijnapally ",
    "Bijnor ",
    "Bijpur ",
    "Bikaner ",
    "Bikapur ",
    "Bikramganj ",
    "Bilari ",
    "Bilasipara ",
    "Bilaspur ",
    "Bilaspur-HP ",
    "Bilaspur-HR ",
    "Bilaspur-UP ",
    "Bilgram ",
    "Bilhaur ",
    "Bilimora ",
    "Billawar ",
    "Bina ",
    "Binka ",
    "Binnaguri ",
    "Birbhum ",
    "Birmaharajpur ",
    "Birmitrapur ",
    "Birpara ",
    "Bisalpur ",
    "Bishnupur ",
    "Bisrampur ",
    "Bissam Cuttack ",
    "Biswanath Chariali ",
    "Boarijore ",
    "Boath ",
    "Bobbili ",
    "Bodhan ",
    "Boipariguda ",
    "Boisar ",
    "Bokajan ",
    "Bokakhat ",
    "Bokaro ",
    "Bolpur ",
    "Bongaigaon ",
    "Bongaon ",
    "Bonli ",
    "Bonth ",
    "Borigumma ",
    "Borsad ",
    "Botad ",
    "Boudh ",
    "Brahmapur ",
    "Brahmavar ",
    "Buchi ",
    "Budaun ",
    "Budbud ",
    "Budgam ",
    "Budhlada ",
    "Buguda ",
    "Buhana ",
    "Bulandshahr ",
    "Buldhana ",
    "Bundi ",
    "Buniadpur ",
    "Burhanpur ",
    "Butibori ",
    "Buxar ",
    "Byndoor ",
    "Cachar ",
    "Canacona ",
    "Chaibasa ",
    "Chail ",
    "Chainpur ",
    "Chakai ",
    "Chakia ",
    "Chakradharpur ",
    "Chala ",
    "Chalakudy ",
    "Chalisgaon ",
    "Challakere ",
    "Chamarajanagar ",
    "Chamba ",
    "Chamkaur Sahib ",
    "hamoli ",
    "Chamorshi ",
    "Champa ",
    "Champawat ",
    "Chanchal ",
    "Chand ",
    "Chandankiyari ",
    "Chandannagar ",
    "Chandauli ",
    "Chandausi ",
    "Chandi ",
    "Chandigarh ",
    "Chandikhol ",
    "Chandil ",
    "Chandipur ",
    "Chandla ",
    "Chandpur ",
    "Chandragiri ",
    "Chandrapur ",
    "Chandwa ",
    "Chandwad ",
    "Channagiri ",
    "Channapatna ",
    "Channarayapatna ",
    "Chapda ",
    "Charkhi Dadri ",
    "Chatra ",
    "Chaufula ",
    "Cheeka ",
    "Chemmad ",
    "Chengalpattu ",
    "Chengam ",
    "Chennai ",
    "Chennur ",
    "Cherthala ",
    "Cheruthoni ",
    "Chevella ",
    "Cheyyar ",
    "Chhabra ",
    "Chhapra ",
    "Chhata ",
    "Chhatarpur ",
    "Chhatarpur-JR ",
    "Chhendipada ",
    "Chhibramau ",
    "Chhindwara ",
    "Chhota Udaipur ",
    "Chidambaram ",
    "Chikhli ",
    "Chikiti ",
    "Chikkaballapura ",
    "Chikkamagaluru ",
    "Chikodi ",
    "Chilakaluripet ",
    "Chimakurthy ",
    "Chimur ",
    "Chincholi ",
    "Chintalapudi ",
    "Chintamani ",
    "Chintapalle ",
    "Chintpurni ",
    "Chiplun ",
    "Chippagiri ",
    "Chipurupalle ",
    "Chirala ",
    "Chirgaon-HP ",
    "Chirimiri ",
    "Chirkunda ",
    "Chitradurga ",
    "Chitrakoot ",
    "Chittoor ",
    "Chittorgarh ",
    "Chityal ",
    "Chodavaram ",
    "Chomu ",
    "Chopal ",
    "Chotila ",
    "Chouparan ",
    "Choutuppal ",
    "Chunar ",
    "Churu ",
    "Coimbatore ",
    "Colonelganj ",
    "Contai ",
    "Cooch Behar ",
    "Coonoor ",
    "Cuddalore ",
    "Cuddapah ",
    "Cumbum-AP ",
    "Cumbum-TN ",
    "Cuttack ",
    "Dabhoi ",
    "Dabhra ",
    "Dabra ",
    "Dabwali ",
    "Dachepalli ",
    "Dadri ",
    "Dahanu ",
    "Dahod ",
    "Dakshin Barasat ",
    "Dakshina Kannada ",
    "Dalhousie ",
    "Dalkhola ",
    "Dalsingh Sarai ",
    "Daltonganj ",
    "Daman ",
    "Damoh ",
    "Dandeli ",
    "Dandisahi ",
    "Danta ",
    "Dapoli ",
    "Darbhanga ",
    "Darjiling ",
    "Darrang ",
    "Darranga Mela ",
    "Daryapur ",
    "Daspur ",
    "Dasuya ",
    "Dataganj ",
    "Datia ",
    "Daudnagar ",
    "Daund ",
    "Daurala ",
    "Dausa ",
    "Davangere ",
    "Dayapar-GJ ",
    "Debagarh ",
    "Debagram ",
    "Dediapada ",
    "Deeg ",
    "Deesa ",
    "Deglur ",
    "Dehgam ",
    "Dehradun ",
    "Dehri on Sone ",
    "Dehurda ",
    "Delhi ",
    "Demow ",
    "Denkanikottai ",
    "Deoband ",
    "Deodar ",
    "Deoghar ",
    "Deoria ",
    "Deosar ",
    "Deotalab ",
    "Depalpur ",
    "Dera Baba Nanak ",
    "Dera Bassi ",
    "DeshNokh ",
    "Devadurga ",
    "Devakottai ",
    "Devarakonda ",
    "Devarkadra ",
    "Devgad ",
    "ewas ",
    "Dhaka ",
    "Dhamangaon ",
    "Dhampur ",
    "Dhamtari ",
    "Dhanbad ",
    "Dhandhuka ",
    "Dhanghata ",
    "Dhar ",
    "Dharamgarh ",
    "Dharamjaigarh ",
    "Dharamkot ",
    "Dharampur ",
    "DharampurHP ",
    "Dharamshala ",
    "Dharapuram ",
    "Dhari ",
    "Dharmabad ",
    "Dharmapuri ",
    "Dharmapuri-TS ",
    "Dharmasthala ",
    "Dharmavaram ",
    "Dharni ",
    "Dharuhera ",
    "Dharwad Outer ",
    "Dhasai ",
    "Dhaulana ",
    "Dhaurahara ",
    "Dheera ",
    "Dhemaji ",
    "Dhenkanal ",
    "Dholi ",
    "Dholpur ",
    "Dhone ",
    "Dhoraji ",
    "Dhrangadhra ",
    "Dhrol ",
    "Dhubri ",
    "Dhule ",
    "Dhulian ",
    "Dhuri ",
    "Dibai ",
    "Dibiyapur ",
    "Dibrugarh ",
    "Didihat ",
    "Didwana ",
    "Digapahandi ",
    "Digboi ",
    "Dighwara ",
    "Dimapur ",
    "Dinanagar ",
    "Dinara ",
    "Dindigul ",
    "Dindori ",
    "Dindori Mh ",
    "Dinhata ",
    "Doddaballapura ",
    "Doiwala ",
    "Domariyaganj ",
    "Domchanch ",
    "Dongargarh ",
    "Dongarkinhi ",
    "Dotma ",
    "Dubrajpur ",
    "Dudu ",
    "Duggirala ",
    "Dukura ",
    "Duliajan ",
    "Dumka ",
    "Dumraon ",
    "Dungarpur ",
    "Durg ",
    "Durgapur ",
    "Durgapur Outer ",
    "Dwaraka Tirumala ",
    "Dwarka ",
    "East Champaran ",
    "East Singhbhum ",
    "Edappal ",
    "Eluru ",
    "Enkoor ",
    "Ernakulam ",
    "Erode ",
    "Erumely ",
    "tah ",
    "Etawah ",
    "Eturnagaram ",
    "Faizabad ",
    "Falka ",
    "Farakka ",
    "Fardapur ",
    "Faridabad ",
    "Faridkot ",
    "Faridpur ",
    "Farrukhabad ",
    "Fatehabad ",
    "Fatehnagar ",
    "Fatehpur ",
    "Fatuha ",
    "Fazilka ",
    "Firozabad ",
    "Firozpur ",
    "Forbesganj ",
    "G. Udayagiri ",
    "Gadag ",
    "Gadarwara ",
    "Gadchiroli ",
    "Gadhada ",
    "Gadhinglaj ",
    "Gadwal ",
    "ajapathinagaram ",
    "Gajapati ",
    "Gajraula ",
    "Galleri ",
    "Gandhidham ",
    "Gandhinagar ",
    "Gangajalghati ",
    "Gangakher ",
    "Gangapur ",
    "Gangarampur ",
    "Gangavathi ",
    "Gangavati ",
    "Gangtok ",
    "Ganjam ",
    "Gannavaram ",
    "Ganpatipule ",
    "Garautha ",
    "Garh ",
    "Garhchiroli ",
    "Garhshankar ",
    "Garhwa ",
    "Gariadhar ",
    "Gariyaband ",
    "Garjanpur ",
    "Gauribidanur ",
    "Gaya ",
    "Gaya Outer ",
    "Ghanashyampur ",
    "Ghanshyampur ",
    "Gharsana ",
    "Ghatal ",
    "Ghatanji ",
    "Ghatgaon ",
    "Ghati Billan ",
    "Ghatol ",
    "Ghatshila ",
    "Ghaziabad ",
    "Ghazipur ",
    "Ghormara ",
    "Ghosi ",
    "Ghugri ",
    "Ghumarwin ",
    "Ghuntagadia ",
    "Giddalur ",
    "Giddarbaha ",
    "Giddha ",
    "Gingee ",
    "Giridih ",
    "Goa ",
    "Goalpara ",
    "Gobichettipalayam ",
    "Gobindpur ",
    "Godabar ",
    "Godda ",
    "Godhra ",
    "Gogamukh ",
    "Gogunda ",
    "Gohana ",
    "Gohpur ",
    "Gokak ",
    "Gokavaram ",
    "Gola ",
    "Golaghat ",
    "Golakganj ",
    "Gomoh ",
    "Gonda ",
    "Gondal ",
    "Gondia ",
    "Gondpipri ",
    "Gonikoppal ",
    "Gooty ",
    "Gopalapuram ",
    "Gopalganj ",
    "Gopalnagar ",
    "Gopiballabpur ",
    "Gorakhpur ",
    "Gorantla ",
    "Gourbathan ",
    "Govardhan ",
    "Govindgarh ",
    "Govindpur ",
    "Greater Noida ",
    "Greater Thane ",
    "Gubbi ",
    "Gudalur ",
    "Gudem Kotha Veedhi ",
    "Gudha Gorji ",
    "Gudivada ",
    "Gudiyattam ",
    "Gudur ",
    "Guhagar ",
    "Gulbarga ",
    "Gumadera ",
    "Gumia ",
    "Gumkhal ",
    "Gumla ",
    "Guna ",
    "Guntakal ",
    "Guntur ",
    "Gunupur ",
    "Gurdaspur ",
    "Gurgaon ",
    "Guruvayoor ",
    "Guskura ",
    "Guwahati ",
    "Gwalior ",
    "H.D.Kote",
    "Habra",
    "Haflong",
    "Hagari Bommanahalli",
    "Haider Nagar",
    "Hailakandi",
    "Hajipur",
    "Hajo",
    "Haldia",
    "Haldwani",
    "Halkarni",
    "Hallikheda",
    "Halol",
    "Halvad",
    "Hamirpur",
    "Handia",
    "Hangal",
    "Hansi",
    "Hanumangarh",
    "Hapur",
    "Harapanahalli",
    "Harda",
    "Hardoi",
    "Haridwar",
    "Harihar",
    "Haringhata",
    "Haripad",
    "Haripurdhar",
    "Harraiya",
    "Harur",
    "Hasanganj",
    "Hasanpur",
    "Hassan",
    "Hathras",
    "Hatta",
    "Haveri",
    "Hazaribagh",
    "Hazira",
    "Hazrat Jandaha",
    "Hebri",
    "Helencha",
    "Hilsa",
    "Himmatnagar",
    "Hindaun",
    "Hindupur",
    "Hingalganj",
    "Hinganghat",
    "Hingoli",
    "Hirekerur",
    "Hiriyur",
    "Hisar",
    "Hodal",
    "Hojai",
    "Honnali",
    "Honnavar",
    "Hooghly",
    "Hooghly Outer",
    "Hosadurga",
    "Hoshangabad",
    "Hoshiarpur",
    "Hoskote",
    "Hospet",
    "Hosur",
    "Hovina Hadagali",
    "Howrah",
    "Hubli",
    "Hubli Outer",
    "Hukeri",
    "Huliyar",
    "Humnabad",
    "Hunsur",
    "Husnabad",
    "Huzurnagar",
    "Hyderabad",
    "Hyderabad Outer",
    "Ibrahimpatnam",
    "Ichalkaranji",
    "Ichapuram",
    "Ichoda",
    "Idar",
    "Idukki",
    "Igatpuri",
    "Ikauna",
    "Ilkal",
    "Imamganj",
    "Imphal",
    "Indapur",
    "Indi",
    "Indore",
    "Irala",
    "Irinjalakuda",
    "Iritty",
    "Islampur",
    "Islampure",
    "Itanagar",
    "Itarsi",
    "Itawa",
    "Jabalpur",
    "Jadcherla",
    "Jagalur",
    "Jagannathprasad",
    "Jagatpur",
    "Jagatsinghpur",
    "Jagdalpur",
    "Jaggampeta",
    "Jaggayyapeta",
    "Jagraon",
    "Jagtial",
    "Jahu",
    "Jaigaon",
    "Jaijaipur",
    "Jaipatna",
    "Jaipur",
    "Jaisalmer",
    "Jaisinghnagar",
    "Jajpur",
    "Jalalabad",
    "Jalalabad-UP",
    "Jalandhar",
    "Jalaun",
    "Jalesar",
    "Jaleswar",
    "Jalgaon",
    "Jalna",
    "Jalore",
    "Jalpaiguri",
    "Jamalpur",
    "Jambusar",
    "Jamjodhpur",
    "Jamkhandi",
    "Jamkhed",
    "Jammalamadugu",
    "Jammikunta",
    "Jammu",
    "Jamnagar",
    "Jamner",
    "Jamshedpur",
    "Jamtara",
    "Jamui",
    "Jangaon",
    "Jangareddygudem",
    "Janjgir-Champa",
    "Jaora",
    "Japla",
    "Jari",
    "Jasdan",
    "Jashpur",
    "Jashpur Nagar",
    "Jassur",
    "Jatara",
    "Jath",
    "Jaunpur",
    "Jawali",
    "Jayankondam",
    "Jaynagar",
    "Jaysingpur",
    "Jehanabad",
    "Jetpur",
    "Jetpur, Pavi-GJ",
    "Jewar",
    "Jeypore",
    "Jhabua",
    "Jhajjar",
    "Jhalawar",
    "Jhalda",
    "Jhalod",
    "Jhanjharpur",
    "Jhansi",
    "Jhargram",
    "Jharsuguda",
    "Jhumri telaiya",
    "Jhunjhunu",
    "Jhunku",
    "Jind",
    "Jirapur",
    "Jodhpur",
    "Joginder Nagar",
    "Jogulamba Gadwal",
    "Jorhat",
    "Jugsalai",
    "Junagadh",
    "Junnar",
    "Junnardeo",
    "K.V.Rangareddy",
    "Kachchh",
    "Kachhera",
    "Kadaba",
    "Kadapa",
    "Kadiam",
    "Kadiri",
    "Kadobahal",
    "Kadri",
    "Kadthal",
    "Kadur",
    "Kagal",
    "Kaghaznagar",
    "Kahalgaon",
    "Kaiga",
    "Kaikaluru",
    "Kaimur-Bhabua",
    "Kaithal",
    "Kakinada",
    "Kakiriguma",
    "Kala Amb",
    "Kalaghatagi",
    "Kalahandi",
    "Kalaigaon",
    "Kalaiyarkovil",
    "Kalanwali",
    "Kalapathar",
    "Kalavad",
    "Kalchini",
    "Kalgachia",
    "Kaligiri",
    "Kalijhora",
    "Kalimela",
    "Kalkulam",
    "Kallakurichi",
    "Kalna",
    "Kalol",
    "KalolHP",
    "Kalpakkam",
    "Kalpetta",
    "Kalwakurthy",
    "Kalyandurg",
    "Kalyani",
    "KalyanpurBR",
    "Kamareddy",
    "Kamarpukur",
    "Kambadur",
    "Kamothe",
    "Kamrup",
    "Kanakpura",
    "Kanchipuram",
    "Kanchipuram Outer",
    "Kandhamal",
    "Kandi",
    "Kangeyam",
    "Kangra",
    "Kanhangad",
    "Kanigiri",
    "Kanjirapalli",
    "Kankavali",
    "Kanker",
    "KankerBR",
    "Kannad",
    "Kannauj",
    "Kannur",
    "Kanpur",
    "Kanpur Dehat",
    "Kantamal",
    "Kanth",
    "Kanti",
    "Kanyakumari",
    "Kapadwanj",
    "Kapurthala",
    "Karad",
    "Karaikal",
    "Karaikudi",
    "Karauli",
    "Karbi Anglong",
    "Karchhana",
    "Kareli",
    "Karera-MP",
    "Karimganj",
    "Karimnagar",
    "Karjan",
    "Karjat",
    "Karkala",
    "Karnal",
    "Karnaprayag",
    "Karsog",
    "Karukachal",
    "Karunagappally",
    "Karur",
    "Karwar",
    "Kasaragod",
    "Kasganj",
    "Kashipur",
    "Katangi",
    "Katihar",
    "Katni",
    "Katoriya",
    "Katra",
    "Katra-BR",
    "Katul",
    "Katwa",
    "Kavali",
    "Kavant",
    "Kaveripattinam",
    "Kawai",
    "Kawardha",
    "Kedla",
    "Kekri",
    "Kendrapara",
    "Kendujhar",
    "Kerakat",
    "Kesali",
    "Keshiari",
    "keshkal",
    "Keshod",
    "Keshoraipatan",
    "Keylong",
    "Khadda",
    "Khaga",
    "Khagaria",
    "Khair",
    "Khairagarh-UP",
    "Khajuraho",
    "Khalari-JR",
    "Khalilabad",
    "Khambhalia",
    "Khambhat",
    "Khamgaon",
    "Khammam",
    "Khanapur",
    "Khanapur-KA",
    "Khandala",
    "Khandwa",
    "Khanna",
    "Khanpur",
    "Khaprakhol",
    "Kharagpur",
    "Kharagpur-BR",
    "Kharar",
    "Khargone",
    "Khariaguda",
    "Kharora",
    "Kharsia",
    "Khatauli",
    "Khatima",
    "Khatra",
    "Khed",
    "Khedbrahma",
    "Kheragarh",
    "Kheralu",
    "Kheri",
    "Kherli",
    "Kherwara",
    "Khetri Nagar",
    "Khinwara",
    "Khirkiya",
    "Khizasarai",
    "Khopoli",
    "Khorda",
    "Khordha",
    "Khundian",
    "Khunti",
    "Khurai",
    "Khurdha",
    "Khurja",
    "Khutar",
    "Khutauna",
    "Kilakarai",
    "Kilimanoor",
    "Kim",
    "Kinnaur",
    "Kirauli",
    "Kishanganj",
    "Kishangarh",
    "Kishorenagar",
    "Kittur",
    "Kochas",
    "Kochi",
    "Kodad",
    "Kodaikanal",
    "Kodinar",
    "Kodumur",
    "Kodungallur",
    "Koduru",
    "Koilkuntla",
    "Kokrajhar",
    "Kolaghat",
    "Kolar",
    "Kolebira",
    "Kolhapur",
    "Kolhar",
    "Kolkata",
    "Kollam",
    "Kollegal",
    "Kollengode",
    "Komana",
    "Komarada",
    "Konark",
    "Konch",
    "Kondagaon",
    "Kondapi",
    "Kondotty",
    "Konnagar",
    "Kopargaon",
    "Koppa",
    "Koppal",
    "Koraput",
    "Koratla",
    "Korba",
    "Koregaon",
    "Korha",
    "Koriya",
    "Kosli",
    "Kota",
    "Kotdwara",
    "Kotgiri",
    "Kothagudem",
    "Kothapeta",
    "Kothavalasa",
    "Kothur",
    "Kotkapura",
    "Kotkhai",
    "Kotputli",
    "Kottakkal",
    "Kottarakkara",
    "Kottayam",
    "Kotturu",
    "Kovilpatti",
    "Kovvur",
    "Koyilandy",
    "Koyyuru",
    "Kozhikode",
    "Krishnagiri",
    "Krishnanagar",
    "Krishnarajanagara",
    "Krishnarajpet",
    "Kuchaikote",
    "Kuchaman City",
    "Kuchinda",
    "Kudal",
    "Kudligi",
    "Kudus",
    "Kullu",
    "Kumarsain",
    "Kumbakonam",
    "Kumta",
    "Kundapura",
    "Kunigal",
    "Kunkuri",
    "Kunnamkulam",
    "Kunnathunad",
    "Kupari",
    "Kuppam",
    "Kurduwadi",
    "Kurebhar",
    "Kurnool",
    "Kurseong",
    "Kurthoul",
    "Kurukshetra",
    "Kushalnagar",
    "Kushinagar",
    "Kushtagi",
    "Kusmi",
    "Kusumanchi",
    "Kuthuparamba",
    "Kutiyana",
    "Lahar",
    "Lahunipara",
    "Lailunga",
    "Lakhandur",
    "Lakhanpur",
    "Lakhimpur",
    "Lakhisarai",
    "Lakhminia",
    "Lakkireddy Palli",
    "Laksar",
    "Lal Gopalganj",
    "Lalganj",
    "Lalitpur",
    "Lalpur-GJ",
    "Lamptaput",
    "Lanja",
    "Lanka",
    "Lasalgaon",
    "Latehar",
    "Latur",
    "Lehra Gaga",
    "Limbdi",
    "Limkheda",
    "Lingapalem",
    "Lingasugur",
    "Lohaghat",
    "Lohardaga",
    "Loharu",
    "Lohawat",
    "Loisingha",
    "Lonand",
    "Lonavala",
    "Lucknow",
    "Lucknow Outer",
    "Ludhiana",
    "Lumding",
    "Lunawada",
    "Luxettipet",
    "M. Rampur",
    "Macherla",
    "Machhali Shahar",
    "Machilipatnam",
    "Madakasira",
    "Madanapalle",
    "Maddur, Mandya",
    "Madhepura",
    "Madhuban",
    "Madhubani",
    "Madhugiri",
    "Madhupur",
    "Madikeri",
    "Madurai",
    "Madwas",
    "Magadi",
    "Mahabubabad",
    "Mahad",
    "Mahadeviya",
    "Mahagama",
    "Mahakalapara",
    "Maham",
    "Maharajganj",
    "Mahasamund",
    "Mahasi",
    "Mahbubnagar",
    "Mahendragarh",
    "Maheshpur",
    "Maheshwar",
    "Mahilpur",
    "Mahnar Bazar",
    "Mahoba",
    "Mahrauni",
    "Mahuva Bhavnagar",
    "Maihar",
    "Mainaguri",
    "Mainpuri",
    "Mairwa",
    "Majhgawa",
    "Majitha",
    "Makhu",
    "Makrana",
    "Maksudangarh",
    "Malancha",
    "Malappuram",
    "Malbazar",
    "Malda",
    "Malegaon",
    "Malerkotla",
    "Malkangiri",
    "Malkapur",
    "Mallapur",
    "Malmaliya",
    "Malout",
    "Malshiras",
    "Malteswar",
    "Malur",
    "Malvan",
    "Mana Madurai",
    "Manali",
    "Mananthavady",
    "Manapparai",
    "Manavadar",
    "Mancherial",
    "Mandangad",
    "Mandapeta",
    "Mandavi",
    "Mandhar",
    "Mandi",
    "Mandi Dabwali",
    "Mandi Gobindgarh",
    "Mandla",
    "Mandrup",
    "Mandsaur",
    "Mandu",
    "Mandvi",
    "Mandya",
    "Manendragarh",
    "Mangalagiri",
    "Mangaldoi",
    "Mangalore",
    "Mangalpur",
    "Mangaon",
    "Mangarol",
    "Manikchak",
    "Manikpur",
    "Manipal",
    "Manjeri",
    "Manjeshwar",
    "Manjhanpur",
    "Manjhaul",
    "Manjlegaon",
    "Mankavu",
    "Manmad",
    "Mannargudi",
    "Mannarkkad",
    "Manoharpur",
    "Mansa",
    "Manthani",
    "Mantralayam",
    "Manugur",
    "Manvi",
    "Marigaon",
    "Marihan",
    "Markapur",
    "Marthandam",
    "Martinganj",
    "Martur",
    "Masaurhi",
    "Mathabhanga",
    "Mathania",
    "Mathura",
    "Mau-UP",
    "Maudaha",
    "Mavelikara",
    "Mawana",
    "Mayani",
    "Mayiladuthurai",
    "Mayurbhanj",
    "Mazbat",
    "Medak",
    "Medinipur",
    "Meerut",
    "Mehkar",
    "Mehmedabad",
    "Mehnajpur",
    "Mehsana",
    "Mejhia",
    "Mekhliganj",
    "Melchhamunda",
    "Melur",
    "Memari",
    "Mendarda",
    "Menhdawal",
    "Merta",
    "Metpally",
    "Mettupalayam",
    "Mettur",
    "Mhaswad",
    "Midnapore",
    "Miraj",
    "Miran Sahib",
    "Mirganj",
    "Miryalaguda",
    "Mirzapur",
    "Mirzapur-WB",
    "Misrikha",
    "Modasa",
    "Modinagar",
    "Moga",
    "Mohali",
    "Mohammad Bazar",
    "Mohammadi",
    "Mohania",
    "Mohanlalganj",
    "Mokama",
    "Molakalmuru",
    "Moodabidri",
    "Morada",
    "Moradabad",
    "Moradabad Outer",
    "Moranhat",
    "Morbi",
    "Morbi Outer",
    "Morena",
    "Morigaon",
    "Moth",
    "Motihari",
    "Motikhavdi",
    "Motipur",
    "Muchipara",
    "Mudal",
    "Muddebihal",
    "Mudhol",
    "Mudhole",
    "Mudigere",
    "Mudinepalli",
    "Mudukulathur",
    "Mughal Sarai",
    "Mukerian",
    "Mukkam",
    "Muktsar",
    "Mulabagilu",
    "Mulbagal",
    "Mumbai",
    "Mummidivaram",
    "Mundgod",
    "Mundra",
    "Munger",
    "Mungpoo",
    "Mungra Badshahpur",
    "Munugode",
    "Murarai",
    "Murbad",
    "Muribahal",
    "Murshidabad",
    "Murtizapur",
    "Murud",
    "Musafirkhana",
    "Musiri",
    "Mussoorie",
    "Muthukuru",
    "Muvattupuzha",
    "Muzaffarpur",
    "Muzaffarpur Outer",
    "Mydukur",
    "Mylavaram",
    "Mysore",
    "Mysore Outer",
    "Nabadwip",
    "Nabarangapur",
    "Nabarangpur",
    "Nabha",
    "Nadaun",
    "Nadia",
    "Nadiad",
    "Nadoti",
    "Nagamangala",
    "Nagaon",
    "Nagapattinam",
    "Nagar",
    "Nagar Untari",
    "Nagari",
    "Nagarkurnool",
    "Nagaur",
    "Nagda",
    "Nagercoil",
    "Nagina",
    "Nagpur",
    "Nahan",
    "Naharlagun",
    "Naidupeta",
    "Naihati",
    "Naina Devi",
    "Nainital",
    "Nainpur",
    "Nainwa",
    "Najibabad",
    "Nakashipara",
    "Nakhatrana",
    "Nakodar",
    "Nakrekal",
    "Nalagarh",
    "Nalanda",
    "Nalbari",
    "Naldurg",
    "Nalgonda",
    "Naliya",
    "Nalkheda",
    "Nallampalli",
    "Namakkal",
    "Nanded",
    "Nandgaon",
    "Nandigama",
    "Nandigram",
    "Nandikotkur",
    "Nandura",
    "Nandurbar",
    "Nandyal",
    "Nanjangud",
    "Nanoor",
    "Naraingarh",
    "Narasannapeta",
    "Narasaraopeta",
    "Narayankhed",
    "Narayanpet",
    "Nargund",
    "Narkatiaganj",
    "Narnaul",
    "Narsampet",
    "Narsapur",
    "Narsapur-TS",
    "Narsinghgarh",
    "Narsinghpur",
    "Narsipatnam",
    "Narwana",
    "Nashik",
    "Nasirabad",
    "Nasvadi",
    "Natham",
    "Naugachia",
    "Nautanwa",
    "Navapur",
    "Navi Mumbai",
    "Navsari",
    "Nawabganj",
    "Nawada",
    "Nawalgarh",
    "Nawanshahr",
    "Naxalbari",
    "Nayagarh",
    "Nedumangad",
    "Neem ka Thana",
    "Neemrana",
    "Neemuch",
    "Nekarikallu",
    "Nellore",
    "Neora",
    "Nepanagar",
    "Nerwa",
    "Netrang",
    "Nevasa",
    "Neyveli",
    "Neyyattinkara",
    "Nichlaul",
    "Nighasan",
    "Nilambur",
    "Nilanga",
    "Nilgiris",
    "Nimapara",
    "Nimbahera",
    "Nipani",
    "Niphad",
    "Nira",
    "Nirmal",
    "Nirmand",
    "Niwari",
    "Nizamabad",
    "Nizamabad-UP",
    "Noamundi",
    "Noida",
    "North 24 Parganas",
    "North Dinajpur",
    "North Lakhimpur",
    "North Paravur",
    "Nowda",
    "Nuaon",
    "Nuapada",
    "Nuh",
    "Nurpur",
    "Nuzvid",
    "Obra",
    "Oddanchatram",
    "Ojhar",
    "Omalur",
    "Onda",
    "Ongole",
    "Ooty",
    "Orai",
    "Oras",
    "Ormanjhi",
    "Osmanabad",
    "Pachora",
    "PadampurRJ",
    "Paddhari",
    "Paderu",
    "Padma",
    "Padrauna",
    "Padubidri",
    "Paikana",
    "Paithan",
    "Pakur",
    "Pala",
    "Palacode",
    "Palai",
    "Palair",
    "Palakkad",
    "Palakollu",
    "Palakonda",
    "Palamaner",
    "Palamau",
    "Palampur",
    "Palani",
    "Palanpur",
    "Palasa, Kasibugga-AP",
    "Palasi",
    "Palghar",
    "Pali",
    "Pali-MH",
    "Palion",
    "Palitana",
    "Palladam",
    "Pallahara",
    "Palojori",
    "Palwal",
    "Palwancha",
    "Pamur",
    "Panchkula",
    "Panchwad",
    "Pandariya",
    "Pandharpur",
    "Pandhurna",
    "Paneri",
    "Panipat",
    "Panipat Outer",
    "Panki",
    "Panna",
    "Panruti",
    "Panskura",
    "Panvel",
    "Paonta Sahib",
    "Paota",
    "Paradip",
    "Parakkadavu",
    "Paramakudi",
    "Paratwada",
    "Parbhani",
    "Parchur",
    "Pargi",
    "Parkal",
    "Parli",
    "Parmanpur",
    "Parsa",
    "Partur",
    "Parvathipuram",
    "Parwanoo",
    "Patan",
    "Patan-CG",
    "Patan-MH",
    "Pataudi",
    "Pathalgaon",
    "Pathanamthitta",
    "Pathankot",
    "Pathapatnam",
    "Patiala",
    "Patkura",
    "Patna",
    "Patna-CH",
    "Patran",
    "Patratu",
    "Pattambi",
    "Patti",
    "Pattikonda",
    "Pattukkottai",
    "Pauri",
    "Pauri Garhwal",
    "Pavagada",
    "Pawai",
    "Payakaraopeta",
    "Payal",
    "Payyanur",
    "Peddapalli",
    "Peddapuram",
    "Pehowa",
    "Pen",
    "Pendurthi",
    "Pennagaram",
    "Penukonda",
    "Perambalur",
    "Perambra",
    "Perinthalmanna",
    "Perumbavoor",
    "Perundurai",
    "Phagwara",
    "Phalodi",
    "Phaltan",
    "Phillaur",
    "Phoolpur",
    "Phulbani",
    "Phusro",
    "Pihani",
    "Pilani",
    "Pileru",
    "Pilibhit",
    "Pilu Khera",
    "Pinjore",
    "Pipariya",
    "Pirangut",
    "Piravom",
    "Piro",
    "Pithampur",
    "Pithoragarh",
    "Plassey",
    "Pochampally",
    "Podili",
    "Pokhriabong",
    "Polasara",
    "Polavaram",
    "Polay Kalan",
    "Pollachi",
    "Ponnani",
    "Ponnur",
    "Poona Chakan",
    "Porbandar",
    "Poriyahat",
    "Pottangi",
    "Pratapgarh",
    "Pratappur",
    "Prathipadu, East Godavari_AP",
    "Prathipadu, Guntur-AP",
    "Prayagraj",
    "Prayagraj Outer",
    "Pregnapur",
    "Prithvipur",
    "Proddatur",
    "Puducherry",
    "Pudukkottai",
    "Pukhrayan",
    "Pulivendula",
    "Puliyangudi",
    "Pullpaly",
    "Pulwama",
    "Punalur",
    "Pune",
    "Pune Outer",
    "Punganur",
    "Punsia",
    "Pupri",
    "Puranakatak",
    "Puranpur",
    "Purba Medinipur",
    "Purbasthali",
    "Puri",
    "Purnia",
    "Purulia",
    "Pusad",
    "Puttaparthi",
    "Puttur",
    "Puttur-AP",
    "Quilandy",
    "Raghogarh",
    "Raghunathganj",
    "Raghunathpur",
    "Raghunathpur-BR",
    "Rahatgarh",
    "Rahimatpur",
    "Raibag",
    "Raichur",
    "Raidighi",
    "Raiganj",
    "Raigarh",
    "Raigarh-MH",
    "Raighar",
    "Raikia",
    "Raikot",
    "Railmagra",
    "Raipur",
    "Raipur Karchulion",
    "Raipur-WB",
    "RaipurRJ",
    "Rairakhol",
    "Raisen",
    "Raisinghnagar",
    "Rajahmundry",
    "Rajakumari",
    "Rajam",
    "Rajampet",
    "Rajamudy",
    "Rajanagaram",
    "Rajapalayam",
    "Rajdhanwar",
    "Rajendragram",
    "Rajgangpur",
    "Rajganj",
    "Rajgarh",
    "Rajgarh-HP",
    "Rajgir",
    "Rajgurunagar",
    "Rajkot",
    "Rajmahal",
    "Rajnandgaon",
    "Rajouri",
    "Rajpipla",
    "Rajpur - CH",
    "Rajpura",
    "Rajsamand",
    "Rajula",
    "Rakkar",
    "Ram Sanehi Ghat",
    "Ramachandrapuram",
    "Ramagundam",
    "Ramanagara",
    "Ramanathapura",
    "Ramanathapuram",
    "Ramannapet",
    "Ramanujganj",
    "Rameswaram",
    "Ramganj Mandi",
    "Ramgarh",
    "Ramgarh-RJ",
    "Ramkrishna Nagar",
    "Ramnad",
    "Ramnagar",
    "Rampachodavaram",
    "Rampur",
    "Rampur Baghelan",
    "Rampur Bushahr",
    "Rampura Phul",
    "Rampurhat",
    "Ramtek",
    "Ranaghat",
    "Ranasthalam",
    "Ranchha",
    "Ranchi",
    "Ranebennur",
    "Rangalia",
    "Rangia",
    "Rania",
    "Ranihati",
    "Ranii",
    "Ranikhet",
    "Raninagar",
    "Ranipet",
    "Ranital",
    "Ranpur",
    "Rapar",
    "Rapur",
    "Rashiwade Bk",
    "Rasipuram",
    "Rasulabad",
    "Ratangarh-MP",
    "Rath",
    "Ratia",
    "Ratlam",
    "Ratlam Outer",
    "Ratnagiri",
    "Ratnari",
    "Raver",
    "Rawatbhata",
    "Rawatsar",
    "Raxaul",
    "Rayachoti",
    "Rayadurgam",
    "Rayagada",
    "Razole",
    "Reckong Peo",
    "Redhills",
    "Rehli",
    "Renukoot",
    "Renwal",
    "Reodar",
    "Repalle",
    "Rewa",
    "Rewari",
    "Riamal",
    "Rishikesh",
    "Rly Koduru",
    "Robertsganj",
    "Rohru",
    "Rohtak",
    "Rohtas",
    "Rona",
    "Roorkee",
    "Roorkee Outer",
    "Rourkela",
    "Rowta",
    "Rudauli",
    "Rudraprayag",
    "Rudrapur",
    "Rudrapur Outer",
    "Runni",
    "Runnisaidpur",
    "Rupbas",
    "Rupnagar",
    "Rusera",
    "Sabalgarh",
    "Sadak Arjuni",
    "Sadam",
    "SADAT",
    "Safipur",
    "Sagar",
    "Sagara",
    "Saharanpur",
    "Saharanpur Outer",
    "Saharsa",
    "Sahaswan",
    "Sahebganj",
    "Sahebpur Kamal",
    "Sahibganj",
    "Sahnewal",
    "Saidpur",
    "Saki Charang",
    "Sakleshpur",
    "Salanpur",
    "Salem",
    "Salem Outer",
    "Salempur",
    "Salipur",
    "Salouni",
    "Salur",
    "Samastipur",
    "Sambalpur",
    "Sambhal",
    "Samrala",
    "Sanawad",
    "Sandhol",
    "Sanduru",
    "Sangameshwar",
    "Sangamner",
    "Sangareddy",
    "Sangli",
    "Sangmeshwar",
    "Sangrur",
    "Sankari",
    "Sant Kabir Nagar",
    "Sant Ravidas Nagar",
    "Santipur",
    "Santrampur",
    "Santuri",
    "Sarada",
    "Saraiya",
    "Saran",
    "Sarangarh",
    "Saray Ankil",
    "Sardarpur",
    "Sardulgarh",
    "Sarthebari",
    "Sarvepalli",
    "Sasaram",
    "Saswad",
    "Satana",
    "Satara",
    "Satbarwa",
    "Sathankulam",
    "Sathupalli",
    "Sathyamangalam",
    "Satna",
    "Sattenapalle",
    "Saundatti",
    "Savarkundla",
    "Savli",
    "Sawai Madhopur",
    "Sawantwadi",
    "Sehore",
    "Semariya",
    "Semiliguda",
    "Seoni",
    "Seraikela-Kharsawan",
    "Seraikella",
    "Shadnagar",
    "Shahabad, Hardoi-UP",
    "Shahabad, Rampur-UP",
    "Shahada",
    "Shahapur",
    "Shahdol",
    "Shahganj",
    "Shahjahanpur",
    "ShahpuraMP",
    "Shajapur",
    "Shamli",
    "Shamsabad",
    "Shamshabad",
    "Shankheshwar",
    "Sharfuddinpur",
    "Shegaon",
    "Sheikhpura",
    "Sheohar",
    "Sheonar",
    "Sheopur",
    "Shevgaon",
    "Shiggaon",
    "Shihori",
    "Shikaripara",
    "Shikaripura",
    "Shikohabad",
    "Shillong",
    "Shimla",
    "Shimoga",
    "Shimoga Outer",
    "Shirahatti",
    "Shirdi",
    "Shirpur",
    "Shirur",
    "Shirur Anantapal",
    "Shivpuri",
    "Shivrinarayan",
    "Shohratgarh",
    "Sholinghur",
    "Shoranur",
    "Shorapur",
    "Shrawasti",
    "Shri Dungargarh",
    "Shri Govindpur",
    "Shrigonda",
    "Shringartali",
    "Shrirampur",
    "Shriwardhan",
    "Shujalpur",
    "Shyampur",
    "Siddapura",
    "Siddharthnagar",
    "Siddipet",
    "Sidhauli",
    "Sidhi",
    "Sihora",
    "Sihunta",
    "Sikandarpur",
    "Sikandra Rao",
    "Sikandrabad",
    "Sikar",
    "Sikriganj",
    "Silapathar",
    "Silchar",
    "Siliguri",
    "Siliguri Outer",
    "Sillod",
    "Silvasa",
    "Silwani",
    "Simalwara",
    "Simdega",
    "Sinapali",
    "Sindagi",
    "Sindewahi",
    "Sindhanur",
    "Sindhudurg",
    "Singanamala",
    "Singhia",
    "Singrauli",
    "Sinnar",
    "Sira",
    "Sirathu",
    "Sirdala",
    "Sirhind, Fatehgarh-PB",
    "Siricilla",
    "Sirigere",
    "Sirkali",
    "Sirkazhi",
    "Sirmaur",
    "Sirohi",
    "Sironcha",
    "Sirsa",
    "Sirsi",
    "Siruguppa",
    "Sitamarhi",
    "Sitapur",
    "Sitarganj",
    "Sivaganga",
    "Sivakasi",
    "Sivasagar",
    "Siwan",
    "Siyana",
    "Sodhana",
    "Sohagi",
    "Sohna",
    "Solan",
    "Solapur",
    "Someshwar",
    "Sompeta",
    "Somwarpet",
    "Sonada",
    "Sonapur",
    "Sonari",
    "Sonbarsa",
    "Sonbhadra",
    "Sonepur-OR",
    "Sonipat",
    "Sonitpur",
    "Soro",
    "South 24 Parganas",
    "South Dinajpur",
    "Sri Dungargarh",
    "Sri Ganganagar",
    "Srikakulam",
    "Srikalahasti",
    "Srinagar",
    "Srinagar-UK",
    "Sringeri",
    "Srirangam",
    "Srirangapatna",
    "Srungavarapukota",
    "Station Ghanpur",
    "Suar",
    "Sugauli",
    "Sugauna",
    "Suigam",
    "Sujangarh",
    "Sukinda",
    "Sullia",
    "Sullurpet",
    "Sultan Bathery",
    "Sultanganj",
    "Sultanpur",
    "Sultanpur Lodhi",
    "Sunam",
    "Sundar Nagar",
    "Sundargarh",
    "Sunderbani",
    "Sundergarh",
    "Sundla",
    "Supaul",
    "Supe",
    "Surajapur",
    "Surajpur jhikla",
    "Surat",
    "Suratgarh",
    "Surathkal",
    "Surendranagar",
    "Surguja",
    "Suri",
    "Suryapet",
    "Swarupnagar",
    "Tadepalligudem",
    "Tadipatri",
    "Tahliwal",
    "Tajpur",
    "Tajpur Dehma",
    "Talaja",
    "Talala",
    "Talasari",
    "Talbehat",
    "Talcher",
    "Talegaon",
    "Talere",
    "Taliparamba",
    "Talod",
    "Talwara",
    "Tamar",
    "Tamarhat",
    "Tamluk",
    "Tanakpur",
    "Tandur",
    "Tandwa",
    "Tanuku",
    "Tarana",
    "Taranagar",
    "Tarapur",
    "Tarikere",
    "Tarkeshwar",
    "Tarn Taran Sahib",
    "Tasgaon",
    "Tauni Devi",
    "Technopark Campus",
    "Tehri Garhwal",
    "Tekkali",
    "Telkoi",
    "Tenali",
    "Tendukheda",
    "Tenkasi",
    "Teok",
    "Test",
    "Tetri Bazar",
    "Tezpur",
    "Thakurmunda",
    "Thalassery",
    "Thallada",
    "Thallarevu",
    "Thamarassery",
    "Thamballapalle",
    "Thane",
    "Thanjavur",
    "Thelamara",
    "Theni",
    "Therlam",
    "Thikri",
    "Thirthahalli",
    "Thiruvadanai",
    "Thiruvananthapuram",
    "Thiruvarur",
    "Thodupuzha",
    "Thoothukudi",
    "Thriprayar",
    "Thrissur",
    "Thuckalay",
    "Thunag",
    "Thuraiyur",
    "Tikamgarh",
    "Tikiri",
    "Tiloi",
    "Tindivanam",
    "Tingkhong",
    "Tinsukia",
    "Tiptur",
    "Tiruchendur",
    "Tiruchengode",
    "Tiruchirapalli",
    "Tirumakudal Narsipur",
    "Tirumangalam",
    "Tirunelveli",
    "Tirupati",
    "Tirupattur",
    "Tiruppattur",
    "Tiruppur",
    "Tirur",
    "Tiruvalla",
    "Tiruvallur",
    "Tiruvallur Outer",
    "Tiruvannamalai",
    "Tiruvarur",
    "Tiruvuru",
    "Tisri",
    "Tista Bazar",
    "Titabor",
    "Titilagarh",
    "Tonk",
    "Toranagallu",
    "Tosham",
    "Tumkur",
    "Tumsar",
    "Tundla",
    "Turuvukere",
    "Tuticorin",
    "Uchchhal",
    "Udaipur",
    "Udaipura",
    "Udaipurwati",
    "Udakishanganj",
    "Udarbond",
    "Udayagiri",
    "Udaynarayanpur",
    "Udgir",
    "Udham Singh Nagar",
    "Udhampur",
    "Udumalaipettai",
    "Udumbanchola",
    "Udupi",
    "Ujire",
    "Ujjain",
    "Ukhunda",
    "Ullal",
    "Ulundurpet",
    "Umaria",
    "Umarkhed",
    "Umarpada",
    "Umbergaon",
    "Umerkote",
    "Umrala",
    "Umred",
    "Umreth",
    "UNA",
    "Una-HP",
    "Unchahar",
    "Undi",
    "Unjha",
    "Unnao",
    "Upleta",
    "Uravakonda",
    "Usilampatti",
    "Uthangarai",
    "Utnoor",
    "Uttarkashi",
    "Uttarnayabad",
    "Vadakara",
    "Vadgam",
    "Vadia",
    "Vadnagar",
    "Vaduj",
    "Vaibhavwadi",
    "Vaikom",
    "Vairag",
    "Vaishali",
    "Valigonda",
    "Vallioor",
    "Valmiki Nagar",
    "Valsad",
    "Vandavasi",
    "Vandiperiyar",
    "Vaniyambadi",
    "Varahi",
    "Varanasi",
    "Varanasi Outer",
    "Vayalpad",
    "Vedaranyam",
    "Veerakkalpudur",
    "Vellakovil",
    "Vellarikundu",
    "Vellore",
    "Vemulawada",
    "Venkatagiri",
    "Venkatagiri Kota",
    "Veraval",
    "Vidisha",
    "Vijapur",
    "Vijayawada",
    "Vijayraghavgarh",
    "Vikarabad",
    "Villupuram",
    "Viluppuram",
    "Vinukonda",
    "Virajpet",
    "Viramgam",
    "Viratnagar",
    "Virpur",
    "Virudhachalam",
    "Virudhunagar",
    "Visakhapatnam",
    "Visavadar",
    "Vita",
    "Vizianagaram",
    "Vuyyuru",
    "Vyara",
    "Wadakkanchery",
    "Wadi",
    "Wadki",
    "Wadrafnagar",
    "Wagholi",
    "Wai",
    "Walchandnagar",
    "Walva",
    "Wanaparthy",
    "Wani",
    "Wankaner",
    "Warangal",
    "Waraseoni",
    "Wardha",
    "Wardhannapet",
    "Washim",
    "Wazirganj",
    "West Champaran",
    "West Singhbhum",
    "Wyra",
    "Yadgir",
    "Yamuna Nagar",
    "Yavat",
    "Yavatmal",
    "Yedrami",
    "Yelamanchili",
    "Yelburga",
    "Yellandu",
    "Yellapur",
    "Yellareddy",
    "Yemmiganur",
    "Yeola",
    "Yerragondapalem",
    "Yerraguntla",
    "Zahirabad",
    "Zamania",
    "Zira",
    "Zirakpur",
  ];

  // Show the "All Cities" dropdown
  viewAllButton.addEventListener("click", () => {
    allCitiesDropdown.classList.add("visible");
  });

  // Close the "All Cities" dropdown
  allCloseButton.addEventListener("click", () => {
    allCitiesDropdown.classList.remove("visible");
  });

  // Populate the city list
  function populateCityList(filteredCities = allCities) {
    allCityList.innerHTML = ""; // Clear previous list
    filteredCities.forEach((city) => {
      const div = document.createElement("div");
      div.textContent = city;
      allCityList.appendChild(div);
    });
  }

  // Populate the alphabet filter
  function populateAlphabetFilter() {
    const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
    alphabet.forEach((letter) => {
      const span = document.createElement("span");
      span.textContent = letter;
      span.addEventListener("click", () => {
        document
          .querySelectorAll(".alphabet-filter span")
          .forEach((s) => s.classList.remove("active"));
        span.classList.add("active");
        const filteredCities = allCities.filter((city) =>
          city.startsWith(letter)
        );
        populateCityList(filteredCities);
      });
      alphabetFilter.appendChild(span);
    });
  }

  // Handle search input
  allSearchBar.addEventListener("input", () => {
    const query = allSearchBar.value.toLowerCase();
    const filteredCities = allCities.filter((city) =>
      city.toLowerCase().startsWith(query)
    );
    populateCityList(filteredCities);
  });

  // Initial population of the list and alphabet filter
  populateCityList();
  populateAlphabetFilter();
});

// chat
function openWhatsapp() {
  window.open("https://wa.me/7290068900", "_blank");
}

function openChat() {
  alert("Live Chat feature coming soon!");
}
